### PR TITLE
Fix of module imports  + large style update 

### PR DESCRIPTION
**Pull request by altavir**
- Fixed module imports for project to be compatible with kotlin-frontend plugin and webpack.
- Update kotlin plugin
- Added kotlin frontend demo
- Fixed style in files. 
- All open policy contradicts to official kotlin policy and makes no sense.

### CODE REVIEW

**Comment by markaren** [comment]
Thanks for the PR. It's quite big though. I wish it was divided into several PRs. E.g update gradle, add frontend-demo, format code etc. 

I will have a look at it eventually, but I probably won't have time the first two weeks.

**Comment by altavir** [comment]
I did not intend to make PR at first. Had to work with JB guys to understand what is broken. And after that it was late to split into smaller changes. We will probably make a permanent fork of the project because we need it for our work.

**Comment by markaren** [comment]
I see. Probably the added demo project do not belong in this repository. It might be better to just add a link to it.

**Comment by markaren** [comment]
While I would like to see some of the changes merged, I will close this PR as a whole. It's to big, and aims to wide. Also I think the additional demo does not belong in this repository.

**Pull request closed without merging**
